server:
  port: 8080
spring:
  application:
    name: "JavaS3"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: "dev"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  aws:
    s3:
      bucketName: "test"
      region: "us-east-1"
      endpoint: "https://s3.localhost.localstack.cloud:4566"
